// ROCK PAPER SCISSORS GAME
//the user will input s,p or r and the computer will also choose one
//if the user wins, it will print "you won the match"
//if the user looses, it will print "you loose the match"
//if the user and computer chooses the same input, it will print
// "match draw"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
int game(char you, char computer)
{
if (you == computer)
return -1;
if (you == 'r' && computer == 'p')
return 0;
else if (you == 'p' && computer == 'r') return 1;
if (you == 'r' && computer == 's')
return 1;
else if (you == 's' && computer == 'r')
return 0;
if (you == 'p' && computer == 's')
return 0;
else if (you == 's' && computer == 'p')
return 1;
}
int main()
{
// Stores the random number generated by the computer
int n;
char you, computer, result;
srand(time(NULL));
n = rand() % 100;
if (n < 33)
// r is denoting Rock
computer = 'r';
else if (n > 33 && n < 66)
// p is denoting Paper
computer = 'p';
// s is denoting Scissor
else
computer = 's';
printf("\t\t\t\tWELCOME TO THE STONE,PAPER & SCISSORS GAME");
printf("\n\n\n\t\t\t\tEnter r for ROCK, p for PAPER and s for SCISSOR\n\t\t\t\t\t\t\t");
scanf("%c", &you);
// Function Call to play the game
result = game(you, computer);
if (result == -1) {
printf("\n\n\t\t\t\tGame Draw!\n");
}
else if (result == 1) {
printf("\n\n\t\t\t\tWow! You have won the game!\n");
}
else if (result == 0) {
printf("\n\n\t\t\t\tOh! You have lost the game!\n");}
else{
printf("\n\n\t\t\t\t\t>>Invalid Character Chosen<<\n");
printf("\n\n\t\t\t\t\nEnter r for ROCK, p for PAPER and s for SCISSOR");}
printf("\t\t\t\tYou choose : %c and Computer choose : %c\n",you, computer);
return 0;
}
